version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: "/"
    groups:
      npm:
        patterns:
          - "*"
    schedule:
      interval: weekly
    cooldown:
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 2
      default-days: 7

  - package-ecosystem: bundler
    directory: "/action_text-trix"
    groups:
      bundler:
        patterns:
          - "*"
    schedule:
      interval: weekly
    cooldown:
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 2
      default-days: 7
