load_paths:
  - test/src
  - test/vendor
  - assets
  - polyfills
  - src

logical_paths:
  - trix.js
  - test.js
  - trix.css

build:
  logical_paths:
    - trix.js
    - trix-core.js
    - trix.css
  path: dist
  js_compressor: uglifier

require:
  - sprockets/export
  - sprockets/svgo

plugins:
  sauce_labs:
    tunnel_timeout: 120
    test_config:
      idle_timeout: 900
      max_duration: 900
    browsers:
      Google Chrome:
        os: Mac, Windows
        version: -2
      Firefox:
        os: Mac, Windows
        version: -2
      Safari:
        platform: Mac
        version: -3
      Microsoft Edge:
        version: 16
      Internet Explorer:
        version: 11
      iPhone:
        version: [11.2, 10.3, 9.3]
      Android:
        version: [6.0, 5.1, 4.4]
