load_paths:
  - test/src
  - test/vendor
  - assets
  - polyfills
  - src

logical_paths:
  - trix.js
  - test.js
  - trix.css

build:
  logical_paths:
    - trix.js
    - trix-core.js
    - trix.css
  path: dist
  js_compressor: uglifier

require:
  - sprockets/export
  - sprockets/svgo
