require 'bundler/setup'

namespace :site do
  desc "Build jekyll site"
  task :build do
    puts "Building..."
    puts `bin/jekyll build`
    puts
  end

  desc "Publish site to S3"
  task publish: :build do
    puts "Publishing..."
    puts `bin/s3_website push`
    puts
  end
end
