import "inspector/templates/debug"
import "inspector/templates/document"
import "inspector/templates/performance"
import "inspector/templates/render"
import "inspector/templates/selection"
import "inspector/templates/undo"
