source "https://rubygems.org"

# Specify your gem's dependencies in trix.gemspec.
gemspec

branch = ENV.fetch("RAILS_BRANCH", "main")
gem "rails", github: "rails/rails", branch: branch
gem "importmap-rails"
gem "propshaft"
gem "puma"
gem "sqlite3"

group :test do
  gem "cuprite", require: "capybara/cuprite"
  gem "minitest", "< 6.0" # can be removed once Rails' line_filtering supports Minitest 6+
end
