Trix.config.css =
  attachment: "attachment"
  attachmentProgress: "attachment__progress"
  attachmentName: "attachment__name"
  attachmentSize: "attachment__size"
  attachmentRemove: "attachment__remove attachment__remove-icon"
  attachmentCaption: "attachment__caption"
  attachmentCaptionEdited: "attachment__caption-edited"
  attachmentCaptionEditing: "attachment__caption-editing"
  attachmentCaptionEditor: "attachment__caption-editor"
