Trix.config.css =
  attachment: "attachment"
  attachmentProgress: "attachment__progress"
  attachmentName: "attachment__name"
  attachmentSize: "attachment__size"
  attachmentCaption: "attachment__caption"
  attachmentCaptionEditor: "attachment__caption-editor"
  attachmentContainer: "attachment-container"
  attachmentGallery: "attachment-gallery"
