Trix.config.lang =
  attachFiles: "Attach Files"
  bold: "Bold"
  bullets: "Bullets"
  byte:  "Byte"
  bytes: "Bytes"
  captionPlaceholder: "Add a caption…"
  code: "Code"
  heading1: "Heading"
  indent: "Increase Level"
  italic: "Italic"
  link: "Link"
  numbers: "Numbers"
  outdent: "Decrease Level"
  quote: "Quote"
  redo: "Redo"
  remove: "Remove"
  strike: "Strikethrough"
  undo: "Undo"
  unlink: "Unlink"
  url: "URL"
  urlPlaceholder: "Enter a URL…"
  GB: "GB"
  KB: "KB"
  MB: "MB"
  PB: "PB"
  TB: "TB"
