Trix.config.lang =
  bold: "Bold"
  italic: "Italic"
  strike: "Strike"
  link: "Link"
  unlink: "Unlink"
  quote: "Quote"
  code: "Code"
  bullets: "Bullets"
  numbers: "Numbers"
  indent: "Indent"
  outdent: "Outdent"
  undo: "Undo"
  redo: "Redo"
  remove: "Remove"
  editCaption: "Edit caption"
  captionPlaceholder: "Type a caption here…"
  urlPlaceholder: "Enter a URL…"
